# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from manipulateDB import *
from Classes.Student import Student

"""
#testing teachers functionality
teacher.setFullName("fullName")
crud(conn, 'u', teacher.updateData()) 

#testing students functionality
student = Student(None, "achraf affes", "gremda km9", "55212353", "supcom", "indp2")
studentId =  crud(conn, 'c', student.insertData()) 
student.setStudentId(studentId)
print(crud(conn, 'r', student.getData()))
student.setLevel("55555")
crud(conn, 'u', student.updateData())
print(crud(conn, 'r', student.getData()))
crud(conn, 'd', student.deleteData())

#testing payments functionality
payment = Payment(None, 1, 3, "1998-08-32", "mathematics", 5, 70)
paymentId =  crud(conn, 'c', payment.insertData()) 
payment.setPaymentId(paymentId)
print(crud(conn, 'r', payment.getData()))
payment.setPrice(500)
crud(conn, 'u', payment.updateData())
conn.close()
"""
class AddStudent_gui(object):
    def setupUi(self, MainWindow):

        self.address_value = None
        self.fullname_value = None
        self.level_value = None
        self.phoneNbr_value = None
        self.establishement_value = None
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 330)
        MainWindow.setMinimumSize(QtCore.QSize(505, 330))
        MainWindow.setMaximumSize(QtCore.QSize(505, 330))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 501, 278))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.address = QtWidgets.QLabel(self.gridLayoutWidget)
        self.address.setObjectName("address")
        self.gridLayout_3.addWidget(self.address, 3, 1, 1, 1)

        self.input_Address = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.input_Address.setObjectName("input_Address")
        self.gridLayout_3.addWidget(self.input_Address, 4, 1, 1, 1)

        self.input_establishement = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.input_establishement.setObjectName("input_establishement")
        self.gridLayout_3.addWidget(self.input_establishement, 13, 1, 1, 1)

        self.phoneNbr = QtWidgets.QLabel(self.gridLayoutWidget)
        self.phoneNbr.setObjectName("phoneNbr")
        self.gridLayout_3.addWidget(self.phoneNbr, 9, 1, 1, 1)
        
        self.input_fullname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.input_fullname.setObjectName("input_fullname")
        self.gridLayout_3.addWidget(self.input_fullname, 1, 1, 1, 1)

        self.level = QtWidgets.QLabel(self.gridLayoutWidget)
        self.level.setObjectName("level")
        self.gridLayout_3.addWidget(self.level, 6, 1, 1, 1)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 1, 1, 1)
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 8, 1, 1, 1)
        
        self.input_phoneNbr = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.input_phoneNbr.setObjectName("input_phoneNbr")
        self.input_phoneNbr.setValidator(QtGui.QIntValidator())
        self.gridLayout_3.addWidget(self.input_phoneNbr, 10, 1, 1, 1)
        
        self.input_level = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.input_level.setObjectName("input_level")
        self.gridLayout_3.addWidget(self.input_level, 7, 1, 1, 1)
        
        self.fullname = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fullname.setObjectName("fullname")
        self.gridLayout_3.addWidget(self.fullname, 0, 1, 1, 1)
        
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        
        self.establishement = QtWidgets.QLabel(self.gridLayoutWidget)
        self.establishement.setObjectName("establishement")
        self.gridLayout_3.addWidget(self.establishement, 12, 1, 1, 1)
        
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 11, 1, 1, 1)
        
        self.addStudentBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addStudentBtn.setGeometry(QtCore.QRect(360, 300, 140, 25))
        self.addStudentBtn.setObjectName("addStudentBtn")
        self.addStudentBtn.clicked.connect(self.onClicked)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ajouter un élève"))
        self.address.setText(_translate("MainWindow", "Address"))
        self.phoneNbr.setText(_translate("MainWindow", "Numéro de téléphone"))
        self.level.setText(_translate("MainWindow", "Niveau"))
        self.fullname.setText(_translate("MainWindow", "Nom et prenom"))
        self.establishement.setText(_translate("MainWindow", "Establishement"))
        self.addStudentBtn.setText(_translate("MainWindow", "Ajouter un élève"))

    def onClicked(self):
        valid = True
        self.address_value = self.input_Address.text()
        self.phoneNbr_value = self.input_phoneNbr.text()
        self.establishement_value = self.input_establishement.text()
        self.fullname_value = self.input_fullname.text()
        self.level_value = self.input_level.text()

        if(len(self.fullname_value)==0):
            valid = False
            self.fullname.setStyleSheet("QLabel#fullname {color : red; }")
        else :
            self.fullname.setStyleSheet("QLabel#fullname {color : black; }")

        if(len(self.address_value)==0):
            valid = False
            self.address.setStyleSheet("QLabel#address {color : red; }")
        else: 
            self.address.setStyleSheet("QLabel#address {color : black; }")

        if(len(self.level_value)==0):
            valid = False
            self.level.setStyleSheet("QLabel#level {color : red; }")
        else:
            self.level.setStyleSheet("QLabel#level {color : black; }")
        
        if(len(self.phoneNbr_value)==0):
            valid = False
            self.phoneNbr.setStyleSheet("QLabel#phoneNbr {color : red; }")
        else: 
            self.phoneNbr.setStyleSheet("QLabel#phoneNbr {color : black; }")

        if(len(self.establishement_value)==0):
            valid = False
            self.establishement.setStyleSheet("QLabel#establishement {color : red; }")
        else:
            self.establishement.setStyleSheet("QLabel#establishement {color : black; }")
        if(valid) :
            self.input_establishement.setText("")
            self.establishement.setStyleSheet("QLabel#establishement {color : black; }")

            self.input_level.setText("")
            self.level.setStyleSheet("QLabel#level {color : black; }")

            self.input_fullname.setText("")
            self.fullname.setStyleSheet("QLabel#fullname {color : black; }")

            self.input_phoneNbr.setText("")
            self.phoneNbr.setStyleSheet("QLabel#phoneNbr {color : black; }")

            self.input_Address.setText("")
            self.address.setStyleSheet("QLabel#address {color : black; }")

            student = Student(None, self.fullname_value, self.address_value, self.phoneNbr_value, 
                self.establishement_value, self.level_value)  
            studentId = crud(conn, 'c', student.insertData())
            student.setStudentId(studentId)
            print(crud(conn, 'r', student.getData()))

    
